all: lab9 test.txt

rebuild: clean all

lab9:
	gcc -o lab9 lab9.c

test.txt:
	echo "fdsaklfjkdasjfkjjaskdjfjklsadjfkljsadfjklasdjfklsjadjfkljsajdfjjskl;dfj;l" > test.txt

clean:
	rm -rf test.txt
	rm -rf lab9